"""empty message

Revision ID: 04400975e3fb
Revises: 71cd04da522c
Create Date: 2022-05-02 20:21:42.970266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04400975e3fb'
down_revision = '71cd04da522c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birth_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birth_date')
    # ### end Alembic commands ###
